### PR TITLE
Add menu for use with subsites.

### PR DESCRIPTION
**Pull request by rupertj**

### CODE REVIEW

**Comment by rupertj** [comment]
Implements #1

**Comment by willguv** [comment]
Nice work @rupertj thanks for starting this!

**Comment by anthonylindsay** [comment]
@rupertj I've had a read through the code changes. I think you've a redundant line here?
https://github.com/localgovdrupal/localgov_subsites_extras/pull/9/files#diff-a69c3da9fe52249117e240c24b3e458807a38c34588bbfa620c0984d65d255cbR65
`$types` doesn't get used anywhere, does it?

**Comment by rupertj** [comment]
@anthonylindsay Good spot. I've fixed that.

**Pull request merged**
