### PR TITLE
Add alter hook to allow other modules to set the subsite homepage.

### PR DESCRIPTION
**Pull request by Polynya**
Add HOOK_localgov_subsites_extras_homepage_alter so that other modules can set the homepage.

As a previous todo says, an event may be better.

### CODE REVIEW

**Comment by Polynya** [comment]
I will add an api.php file

**Comment by rupertj** [comment]
I'm going to suggest we go with my PR #16 in favour of this one.

My reasoning is:
* They both do almost the same thing. I haven't tried it yet, but it should be possible to run the exact code from Adrian's issue in the hook from PR 16, and it should work.
* The main difference between the two is that 16 works before the existing code that walks up the menu tree to check for the current node being part of a subsite, whereas this one runs after it. This means that hook implementations for things like guides only need to return the parent node for guide pages, and the module will figure out if the parent node is part of a subsite. Doing it after means they'd need to check the reference to the parent node, then walk the tree on that node themselves. The method that does that in the service is currently private, so that'd need to change too.
* PR 16 is further along than this one: it's got an api.php, tests, and hooks implemented to work with guides and directories.

I think it's a good sign that we've both implemented pretty much the same thing though, it's a good sign that there's a need for this beyond our individual requirements.

**Comment by Polynya** [comment]
Yeah, I'm happy to close this once I've tried PR 16

**Comment by Polynya** [comment]
Closing in favour of PR 16

**Pull request closed without merging**
