### PR TITLE
Placed menu block for subsites by default.

### PR DESCRIPTION
**Pull request by rupertj**
Implements #13.

NB that this uses the default block placement mechanism from https://github.com/localgovdrupal/localgov_core/pull/212.

I've been testing this PR with this line in composer to use that version of localgov_core:
```
"localgovdrupal/localgov_core": "dev-feature/2.x/211-installing-blocks as 2.13.2",
```

### CODE REVIEW

**Comment by finnlewis** [comment]
Hey @rupertj 

Just looking at this one alongside https://github.com/localgovdrupal/localgov_core/pull/212

Tried this : 

1. fresh install of localgov profile
2. enable the localgov_subsites_extras
3. look for the Subsites menu at admin/structure/block
4. Not seeing it

I note that localgov_subsites_extras does not seem to depend on localgov_subsites. Is that by design?

**Comment by finnlewis** [comment]
Tested like this: 

Fresh install of LocalGov Drupal codebase.

```
ddev composer require "localgovdrupal/localgov_core:dev-feature/2.x/211-installing-blocks as 2.13.2" -W
ddev composer require "localgovdrupal/localgov_subsites_extras:dev-feature/1.x/13-place-menu-block as 1.0.0-alpha1" -W
ddev drush si localgov -y; 
ddev drush en localgov_subsites_extras -y; 
ddev drush uli;
```
Then checked that the "Subsiites menu" block is placed in the "Subsites menu" region, which it is now!

Thanks @rupertj - this part of it seems to be working.

**Comment by markconroy** [comment]
@finnlewis from your last comment, it looks like this should be marked as 'Approved', or is there something more that needs doing?

**Comment by rupertj** [comment]
@markconroy This needs the PR to localgov_core that I mentioned in the first comment to land first.

**Comment by markconroy** [comment]
We need a 'blocked' label I think 😄

**Comment by finnlewis** [comment]
@rupertj is this ready to go now? https://github.com/localgovdrupal/localgov_core/pull/212 has been merged.

**Comment by rupertj** [comment]
Yes it is!

**Pull request merged**
