### PR TITLE
Add subsites cache context.

### PR DESCRIPTION
**Pull request by Polynya**

### CODE REVIEW

**Comment by rupertj** [comment]
Thanks for this - it's nice to see the start of being able to override the branding :)

One thing I'm wondering is if the name of the context properly reflects what it is. Currently it's just "subsites" and it returns the value of the current subsite theme.

I'm thinking it could be better to have "subsite" and "subsite.theme" as contexts, as you might feasibly want to have two different subsites using the same colour scheme, but with different logos. "subsite" could just use the nid of the root node as its value.

**Comment by Polynya** [comment]
I meant to point out that it uses the theme. 

Following the patterns here: https://www.drupal.org/docs/drupal-apis/cache-api/cache-contexts
I think we could have:
- _subsites.homepage_ (subsites overview node id)
- _subsites.theme_ (visual theme)
- _subsites_ (I'm not sure but either of these?)

**Comment by rupertj** [comment]
Ok, let's go for that. I think subsites by itself should be the node id, so I'll implement it like that.

**Review by rupertj — CHANGES_REQUESTED** [review]
Changes as discussed in issue. (Just marking this as needs changes so it doesn't keep popping up in merge Tuesday...)

**Review by rupertj — APPROVED** [review]

**Comment by rupertj** [comment]
@Polynya I've made the changes. Care to give it a review?

**Comment by Polynya** [comment]
Looks good to me, thanks

**Pull request merged**
